/*
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
*/

function sumEvenfibonacci(num) {
  let evenCount = 0;
  let num1 = 0;
  let num2 = 1;
  let sum;
  let i = 0;
  for (i = 0; i < num; i++) {
    sum = num1 + num2;
    if (sum % 2 === 0) {
      evenCount += sum;
    }
    num1 = num2;
    num2 = sum;
  }
  return evenCount;
}

function EulerProject2() {
  const LIMIT = 32; // above this number, we have above 4million fib number
  return sumEvenfibonacci(LIMIT);
}

EulerProject2();
